### ISSUE TITLE
slow_control_table does not respond to ping

### ISSUE THREAD

**Issue by guiguem** [project8/dragonfly#108] opened 2017-05-25 16:36 UTC
For some mystical reasons, the slow_control_table does not respond to ping.
SensorLogger inherits from Gogol and PostgreSQLInterface:
```python
class SensorLogger(Gogol, PostgreSQLInterface):
    '''
    Project 8 slow control table implementation
    '''
    def __init__(self, sensor_type_map_table, data_tables_dict={}, **kwargs):
        '''
        sensor_type_map_table (str): name of the child endpoint of this instance which provides access to the endpoint_id_map, which stores the sensor type
        data_tables_dict (dict): dictionary mapping types (in the sensor_type_map_table) to child endpoints of this instance which provide access to the data_table for that type
        '''
        # listen to sensor_value alerts channel
        kwargs.update({'keys':['sensor_value.#']})
        Gogol.__init__(self, **kwargs)
        PostgreSQLInterface.__init__(self, **kwargs)
```
All the other Gogol-based services (slack_interface, disk_monitor...) are responsive to ping.

**Comment by laroque** [comment] 2017-05-25 17:43
Do we really have something called `slow_control_interface` that I'm not finding? If so we should change that immediately because it is a pretty meaningless name. I assume the issue is being seen on the service named `slow_control_table`, is that correct?

**Comment by wcpettus** [comment] 2017-08-11 23:04
This was a two-level problem, but the root cause is typical of the nightmares of double-inheritance.

1. `add_endpoint` is overridden by both SensorLogger and PostgreSQLInterface, and so it bypasses the natural functionality of Spimescape.  This is fixed by rerouting the SensorLogger `add_endpoint` method to redirect to both the Spimescape (routed through Gogol, just in case we ever overwrite it there) and the PostgreSQLInterface versions.  Because PostgreSQLInterface is actually a Provider and reroutes through the Provider method it overwrites, this now needs to be conditional to prevent the warnings that have been written into Provider (or those warnings need to be removed)
1. Initializing PostgreSQLInterface (a Provider) after Gogol causes the self._endpoints list to get erased, so the initialization order had to be flipped.

This is testing on the tritium system and appears stable, so it should get picked up in the next release.

**Closed by wcpettus** 2017-08-11 23:04 UTC
Labels: bug
