### ISSUE TITLE
exchange alerts error with kv_store_tutorial.yaml

### ISSUE THREAD

**Issue by les67** [project8/dragonfly#33] opened 2016-04-12 20:02 UTC
When starting the my_store service with the kv_store_tutorial.yaml the following error is produced:

404, "NOT_FOUND - no exchange 'alerts' in vhost '/'"`

The service will run without crashing regardless but the above error is present multiple times when the service starts up.

**Comment by les67** [comment] 2016-04-12 20:06
Running the monitor service simultaneously fixes the error. The message monitor creates the alerts exchange needed by the service at start up to ensure that exchanges exist.

**Comment by laroque** [comment] 2016-04-12 20:11
The service class is supposed to ensure that host exists in the same way that the message_monitor does. The above is a work around but the service class should be fixed.

**Comment by laroque** [comment] 2016-11-07 18:45
duplicate of dripline issue 160

**Closed by laroque** 2016-11-07 18:45 UTC
